version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogger-app-container
    command: ["./wait-for-db.sh", "blogger-db", "python", "main.py"]  # start app after db starts.
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SERVER: blogger-db
      DB_PORT: 5432
      DB_NAME: blogger
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      PYTHONUNBUFFERED: 1
    depends_on:
      - blogger-db

  blogger-db:
    image: postgres:15
    container_name: blogger-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogger
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql  # initial script to create a user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: