services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogger-app-container
    command: ["./wait-for-db.sh", "blogger-db", "python", "main.py"]  # start app after db starts.
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - blogger-db

  blogger-db:
    image: postgres:15
    container_name: blogger-db-container
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-user.sh:/docker-entrypoint-initdb.d/init-user.sh 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: