#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE $INIT_ROLE WITH SUPERUSER LOGIN PASSWORD '$INIT_PWD';
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $INIT_ROLE;
EOSQL
